### ISSUE TITLE
[TASK] Create logo, favicons, and set color theme

### ISSUE THREAD

**Issue by MahdadGhasemian** [oneclickteach/oneclickteach-home#1]
**What is your question?**
Please design and create a logo and favicons for the project, and set an appropriate color theme for the site.

**Context**
We need unique branding assets (logo, favicons) and a consistent color palette for the project. This will help improve project identity and UI consistency.

**Additional information**
- Logo should be scalable and suitable for web use
- Favicons should cover standard web sizes (16x16, 32x32, etc.)
- Color theme should match the intended branding direction
- Please provide assets in SVG/PNG formats and document color codes used

**Comment by MahdadGhasemian** [comment]
```css
:root {
  --primary: #0A6C26;      /* Buttons, headers, navigation */
  --background: #FBF9F1;   /* Page backgrounds, cards */
  --accent-light: #F6BBA3; /* Hover states, highlights */
  --accent-medium: #F27E55; /* CTAs, notifications */
  --accent-strong: #EE4107; /* Alerts, "one-click" elements */
}
```

![Image](https://github.com/user-attachments/assets/55e99399-6953-4171-b332-474d048cf4fe)

![Image](https://github.com/user-attachments/assets/74e89741-c911-46e5-b7cf-33470055efb6)


[favicon_icon.zip](https://github.com/user-attachments/files/20572767/favicon_icon.zip)
